[package]
name="avif-decoder_dep"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "*" , features = ["avif-native"] }

[target.'cfg(any(target_arch = "x86",target_arch = "x86_64"))'.dependencies.image]
version = "*"
default-features = false
features = ["nasm"]
